exports.text = `Thank you. It is a great honor to be invited by you, Mr. President. A great, great honor, thank you.
We had a very substantive, direct and constructive exchange of ideas over quite a period of time. I was straight forward in presenting my views about the impacts of current trade and immigration policies on the United States.
As you know, I love the United States very much and we want to make sure that the people of the United States are very well protected. You equally expressed your feelings and your love for Mexico.
The United States and Mexico share a 2,000-mile border, a half a trillion dollars in annual trade and one million legal border crossings each and every day. We are united by our support for democracy, a great love for our people and the contributions of millions of Mexican Americans to the United States.
And I happen to have a tremendous feeling for Mexican Americans not only in terms of friendships, but in terms of the tremendous numbers that I employ in the United States and they are amazing people, amazing people. I have many friends, so many friends and so many friends coming to Mexico and in Mexico. I am proud to say how many people I employ.
And the United States first, second and third generation Mexicans are just beyond reproach. Spectacular, spectacular hard-working people. I have such great respect for them and their strong values of family, faith and community.
We all share a common interest in keeping our hemisphere safe, prosperous and free. No one wins in either country when human smugglers and drug traffickers prey on innocent people, when cartels commit acts of violence, when illegal weapons and cash flow from the United States into Mexico or when migrants from Central America make the dangerous trek — and it is very, very dangerous — into Mexico or the United States without legal authorization.
I shared my strong view that NAFTA has been a far greater benefit to Mexico than it has been to the United States and that it must be improved upon to make sure that workers, and so important, in both countries benefit from fair and reciprocal trade.
I expressed that to the United States and in — that of the United States, that we must take action to stem this tremendous outflow of jobs from our country. It’s happening every day, it’s getting worse and worse and worse, and we have to stop it. Prosperity and happiness in both of our countries will increase if we work together on the following five shared goals.
Number one, ending illegal immigration, not just between our two countries, but including the illegal immigration and migration from Central and South Americans, and from other regions that impact security and finances, in both Mexico and the United States.
This is a humanitarian disaster. The dangerous treks, the abuse by gangs and cartels and the extreme physical dangers and it must be solved, it must be solved quickly. Not fair to the people, anywhere world wide, you can truly say, but certainly not fair to the people of Mexico and the people of the United States.
Number two, having a secure border is a sovereign right and mutually beneficial. We recognize and respect the right of either country to build a physical barrier or wall on any of its borders to stop the illegal movement of people, drugs and weapons. Cooperation toward achieving the shared objective, and it will be shared of safety for all citizens is paramount, to both the United States and to Mexico.
Number three, dismantling drug cartels and ending the movement of illegal drugs, weapons, and funds across our border. This can only be done with cooperation, intelligence and intelligence sharing and joint operations between our two countries. It’s the only way it’s going to happen. Improving NAFTA, number four. NAFTA is a 22 year old agreement that must be updated to reflect the realities of today.
There are many improvements that could be made that would make both Mexico and the United States stronger and keep industry in our hemisphere. We have tremendous competition from China and from all over the world. Keep it in our hemisphere. Workers in both of our countries need a pay raise, very desperately. In the United States, it’s been 18 years, 18 years wages are going down. Improving pay standards and working conditions will create better results for all and all workers in particular. There’s a lot of value that can be created for both countries by working beautifully together. And that I am sure will happen.
Number five, keep manufacturing wealth in our hemisphere. When jobs leave Mexico, the U.S. or Central America and go over seas, it increases poverty and pressure on social services as well as pressures on cross border migration. Tremendous pressure. The bond between our two countries is deep and sincere. And both our nations benefit from a close and honest relationship between our two governments.
A strong prosperous and vibrant Mexico is in the best interest of the United States and will keep and help keep, for a long, long period of time, America together. Both of our countries will work together for mutual good, and most importantly for the mutual good of our people. Mr. President, I want to thank you. It’s been a tremendous honor and I call you a friend. Thank you.`
